export const COMPLETE_SHELF_TYPOGRAPHY = {
  headingFont: "iowan-old-style",
  bodyFont: "inter",
  headingWeight: "400",
  bodyWeight: "400",
  primaryColor: "#c87046",
  headingSize: 60,
  bodySize: 12,
  headingLetterSpacing: -0.055,
};

export const ANTHRA_A40_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const ATTUNE_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const AURELLO_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const AXONIS_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const BESTSELLERS_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const BETAWISE_HERO_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const BETAWISE_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const INKBOUND_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const ECHO_VALE_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const HALVORSEN_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const KAGE_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const KAIRO_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const MK78_KEYBOARD_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const MARA_VOSS_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const NOEMA_N1_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const RENDERLAB_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const MENG_TO_SKETCHBOOK_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const NOCTURNE_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const SYLVA_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const TIDECREST_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
export const VOLTA_ATELIER_TYPOGRAPHY = { ...COMPLETE_SHELF_TYPOGRAPHY };
